apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tjipr7qju-python
  janus-idp.io/tekton: tjipr7qju-python
  backstage.io/kubernetes-id: tjipr7qju-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tjipr7qju-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
