apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tjipr7qju-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tjipr7qju-python 
  name: tjipr7qju-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tjipr7qju-python 
